use axum::{
    extract::Request,
    http::StatusCode,
    middleware::Next,
    response::{IntoResponse, Response},
};
use std::sync::Arc;
use subtle::ConstantTimeEq;

/// Middleware that enforces `Authorization: Bearer <token>` on every request.
///
/// Without this, any process on the same machine can query the sidecar by
/// connecting to 127.0.0.1:3030. The token is generated by the caller at
/// startup and shared out-of-band (env var).
///
/// `expected_token` is `Arc<str>` so the closure that spawns this function
/// clones a pointer (one atomic increment) instead of heap-allocating a new
/// String per request.
pub async fn bearer_auth(req: Request, next: Next, expected_token: Arc<str>) -> Response {
    let auth_header = req
        .headers()
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok());

    match auth_header {
        Some(header) => {
            let provided = extract_bearer_token(header).unwrap_or("");
            // subtle::ConstantTimeEq examines every byte regardless of content,
            // preventing timing-based token oracle attacks. The comparison
            // intentionally includes length: mismatched-length tokens always
            // compare against a zero-length slice so timing leaks no information
            // about the expected token length.
            if verify_bearer_token(provided.as_bytes(), expected_token.as_bytes()) {
                next.run(req).await
            } else {
                (StatusCode::UNAUTHORIZED, "Invalid token").into_response()
            }
        }
        None => (StatusCode::UNAUTHORIZED, "Missing Authorization header").into_response(),
    }
}

/// Strips the `Bearer ` scheme prefix from an Authorization header value.
///
/// RFC 6750 §2.1 specifies that the auth-scheme token is case-insensitive
/// (`Bearer`, `bearer`, `BEARER` are all valid). Returns `None` if the header
/// does not start with any recognised casing of `"Bearer "`.
pub fn extract_bearer_token(header: &str) -> Option<&str> {
    header
        .get(0..7)
        .and_then(|prefix| {
            if prefix.eq_ignore_ascii_case("Bearer ") {
                header.get(7..)
            } else {
                None
            }
        })
}

/// Constant-time comparison of a provided bearer token against the expected
/// value. Uses `subtle::ConstantTimeEq` so the comparison time does not vary
/// with the position of the first differing byte.
pub fn verify_bearer_token(provided: &[u8], expected: &[u8]) -> bool {
    provided.ct_eq(expected).into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verify_bearer_token_accepts_correct_token() {
        let token = b"correct-token-value-32-chars-xxxx";
        assert!(verify_bearer_token(token, token));
    }

    #[test]
    fn verify_bearer_token_rejects_wrong_token() {
        let expected = b"correct-token-value-32-chars-xxxx";
        let wrong = b"wrong---token-value-32-chars-xxxx";
        assert!(!verify_bearer_token(wrong, expected));
    }

    #[test]
    fn verify_bearer_token_rejects_empty_vs_nonempty() {
        assert!(!verify_bearer_token(b"", b"nonempty"));
        assert!(!verify_bearer_token(b"nonempty", b""));
    }

    #[test]
    fn extract_bearer_token_canonical() {
        assert_eq!(extract_bearer_token("Bearer abc123"), Some("abc123"));
    }

    #[test]
    fn extract_bearer_token_lowercase() {
        assert_eq!(extract_bearer_token("bearer abc123"), Some("abc123"));
    }

    #[test]
    fn extract_bearer_token_uppercase() {
        assert_eq!(extract_bearer_token("BEARER abc123"), Some("abc123"));
    }

    #[test]
    fn extract_bearer_token_rejects_basic() {
        assert_eq!(extract_bearer_token("Basic dXNlcjpwYXNz"), None);
    }

    #[test]
    fn extract_bearer_token_rejects_empty() {
        assert_eq!(extract_bearer_token(""), None);
    }
}
